name: 🔨 Build Test
on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  build:
    name: Test Builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        run: go test .
        working-directory: cmd/dnsx/

      - name: Build
        run: go build .
        working-directory: cmd/dnsx/
